openapi: 3.0.0
info:
  title: 氣象資料開放平台
  version: 1.0.0
servers:
  - url: https://opendata.cwa.gov.tw/api
paths:
  /v1/rest/datastore/F-C0032-001:
    get:
      description: 臺灣各縣市天氣預報資料及國際都市天氣預報
      summary: 一般天氣預報-今明 36 小時天氣預報
      parameters:
        - name: Authorization
          in: query
          description: 氣象開放資料平台會員授權碼
          required: true
          schema:
            type: string
        - name: format
          in: query
          description: 回傳資料格式，預設為 json 格式
          schema:
            type: string
            default: JSON
        - name: locationName
          in: query
          description: 臺灣各縣市，預設為回傳全部縣市
          schema:
            enum:
               - 基隆市
               - 臺北市
               - 宜蘭縣
               - 嘉義縣
               - 彰化縣
               - 新竹縣
               - 苗栗縣
               - 澎湖縣
               - 新竹市
               - 屏東縣
               - 南投縣
               - 花蓮縣
               - 嘉義市
               - 臺東縣
               - 雲林縣
            type: string
      responses:
        '200':
          description: 成功響應
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: object
                    properties:
                      resource_id:
                        type: string
                      fields:
                        type: array
                        items:
                          type: object            
  /v1/rest/datastore/M-A0085-001:
    get:
      description: 健康氣象相關數值預報資料-熱傷害分級與綜合溫度熱指數
      summary: 健康氣象-熱傷害指數及警示全台各鄉鎮五日逐三小時預報
      parameters:
        - name: Authorization
          in: query
          description: 氣象開放資料平台會員授權碼
          required: true
          schema:
            type: string
        - name: format
          in: query
          description: 回傳資料格式, 預設為 json 格式
          schema:
            type: string
            default: JSON
        - name: CountyName
          in: query
          description: 各縣市名稱，預設為全部回傳
          schema:
            type: string
      responses:
        '200':
          description: 成功響應
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: object
                    properties:
                      resource_id:
                        type: string
                      fields:
                        type: array
                        items:
                          type: object                                